from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Any

import yaml

from EigenIPC.PyEigenIPC import Journal, LogType


def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as stream:
        data = yaml.safe_load(stream) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return data


def _replace_pwd(value: Any, runtime_dir: Path) -> Any:
    if isinstance(value, str):
        return value.replace("$PWD", str(runtime_dir))
    if isinstance(value, list):
        return [_replace_pwd(item, runtime_dir) for item in value]
    if isinstance(value, dict):
        return {key: _replace_pwd(item, runtime_dir) for key, item in value.items()}
    return value


def _runtime_name(
    xbot_config_path: Path,
    impedance_config_path: Path,
    urdf_path: Path,
    srdf_path: Path,
) -> str:
    token = hashlib.sha1(
        (
            f"{xbot_config_path.resolve()}::"
            f"{impedance_config_path.resolve()}::"
            f"{urdf_path.resolve()}::"
            f"{srdf_path.resolve()}"
        ).encode("utf-8")
    ).hexdigest()[:10]
    return f"{xbot_config_path.stem}.{token}.runtime.yaml"


def _set_xbotinterface_paths(
    runtime_config: dict[str, Any],
    urdf_path: Path,
    srdf_path: Path,
) -> None:
    xbotinterface = runtime_config.setdefault("XBotInterface", {})
    if not isinstance(xbotinterface, dict):
        raise ValueError("XBotInterface section must be a YAML mapping")

    xbotinterface["urdf_path"] = str(urdf_path)
    xbotinterface["srdf_path"] = str(srdf_path)


def build_xbot_runtime_config(
    xbot_config_path: str,
    impedance_config_path: str,
    urdf_path: str,
    srdf_path: str,
    output_dir: str,
) -> str:
    xbot_config = Path(xbot_config_path).expanduser().resolve()
    impedance_config = Path(impedance_config_path).expanduser().resolve()
    urdf = Path(urdf_path).expanduser().resolve()
    srdf = Path(srdf_path).expanduser().resolve()
    out_dir = Path(output_dir).expanduser().resolve()

    for label, path in (
        ("XBot config", xbot_config),
        ("impedance config", impedance_config),
        ("URDF", urdf),
        ("SRDF", srdf),
    ):
        if not path.is_file():
            raise FileNotFoundError(f"{label} not found: {path}")

    runtime_config = _replace_pwd(_load_yaml(xbot_config), xbot_config.parent)
    impedance = _load_yaml(impedance_config)

    for section in ("motor_pd", "startup_motor_pd"):
        if section not in impedance:
            raise ValueError(f"{impedance_config} is missing required section '{section}'")
        runtime_config[section] = impedance[section]

    if "motor_vel" in impedance:
        runtime_config["motor_vel"] = impedance["motor_vel"]

    _set_xbotinterface_paths(runtime_config, urdf, srdf)

    out_dir.mkdir(parents=True, exist_ok=True)
    output_path = out_dir / _runtime_name(xbot_config, impedance_config, urdf, srdf)
    with output_path.open("w", encoding="utf-8") as stream:
        yaml.safe_dump(runtime_config, stream, sort_keys=False)

    return str(output_path)


class XbotRuntimeConfigMixin:
    """Mixin for world interfaces that drive an XBot model (XMJ, RT deploy).

    Builds a runtime XBot config under /tmp from the *template* xbot config + the
    template impedance config + the URDF/SRDF generated by the interface, and points
    the interface's impedance config at it. This is XBot-specific and therefore lives
    in AugMPCEnvs, not in the generic AugMPCWorldInterfaceBase (which must stay
    backend-agnostic). It only relies on attributes provided by the base interface:
    ``_env_opts``, ``_urdf_dump_paths``, ``_srdf_dump_paths``, ``_jnt_imp_config_paths``.
    """

    def _prepare_xbot_runtime_config(self, robot_name: str):
        if not hasattr(self, "_xbot_runtime_config_paths"):
            self._xbot_runtime_config_paths = {}

        xbot_config_path = self._env_opts.get("xbot_config_path", None)
        if xbot_config_path is None:
            xbot_config_path = self._env_opts.get("xbot_config", None)
        if xbot_config_path is None:
            return self._jnt_imp_config_paths[robot_name]

        if robot_name not in self._urdf_dump_paths or robot_name not in self._srdf_dump_paths:
            Journal.log(self.__class__.__name__,
                "_prepare_xbot_runtime_config",
                "URDF/SRDF must be generated before preparing the XBot runtime config",
                LogType.EXCEP,
                throw_when_excep=True)

        output_base = self._env_opts.get("xbot_runtime_config_dir", None)
        if output_base is None:
            output_base = os.path.join("/tmp/ibrido_xbot_configs", robot_name)

        runtime_config = build_xbot_runtime_config(
            xbot_config_path=xbot_config_path,
            impedance_config_path=self._jnt_imp_config_paths[robot_name],
            urdf_path=self._urdf_dump_paths[robot_name],
            srdf_path=self._srdf_dump_paths[robot_name],
            output_dir=output_base,
        )
        self._xbot_runtime_config_paths[robot_name] = runtime_config
        self._jnt_imp_config_paths[robot_name] = runtime_config
        Journal.log(self.__class__.__name__,
            "_prepare_xbot_runtime_config",
            f"Prepared XBot runtime config for {robot_name}: {runtime_config}",
            LogType.STAT,
            throw_when_excep=True)
        return runtime_config
